/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ouyang_camera_CameraStreamReceiver */

#ifndef _Included_com_ouyang_camera_CameraStreamReceiver
#define _Included_com_ouyang_camera_CameraStreamReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ouyang_camera_CameraStreamReceiver
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_camera_CameraStreamReceiver_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_ouyang_camera_CameraStreamReceiver
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_camera_CameraStreamReceiver_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_ouyang_camera_CameraStreamReceiver
 * Method:    start
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILcom/ouyang/camera/StreamHandler;)I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_camera_CameraStreamReceiver_start
  (JNIEnv *, jobject, jstring, jint, jstring, jint, jobject);

/*
 * Class:     com_ouyang_camera_CameraStreamReceiver
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_camera_CameraStreamReceiver_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
