/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ouyang_srtp_SrtpStreamReceiver */

#ifndef _Included_com_ouyang_srtp_SrtpStreamReceiver
#define _Included_com_ouyang_srtp_SrtpStreamReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ouyang_srtp_SrtpStreamReceiver
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_srtp_SrtpStreamReceiver_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_ouyang_srtp_SrtpStreamReceiver
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_srtp_SrtpStreamReceiver_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_ouyang_srtp_SrtpStreamReceiver
 * Method:    start
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILcom/ouyang/srtp/SrtpStreamHandler;)I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_srtp_SrtpStreamReceiver_start
  (JNIEnv *, jobject, jstring, jint, jstring, jint, jobject);

/*
 * Class:     com_ouyang_srtp_SrtpStreamReceiver
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_srtp_SrtpStreamReceiver_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
