/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ouyang_camera_CameraStreamSender */

#ifndef _Included_com_ouyang_camera_CameraStreamSender
#define _Included_com_ouyang_camera_CameraStreamSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ouyang_camera_CameraStreamSender
 * Method:    initialize
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_camera_CameraStreamSender_initialize
  (JNIEnv *, jobject, jstring, jint, jstring, jint);

/*
 * Class:     com_ouyang_camera_CameraStreamSender
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_camera_CameraStreamSender_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_ouyang_camera_CameraStreamSender
 * Method:    sendto
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_ouyang_camera_CameraStreamSender_sendto
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
